const router = require("express").Router();
const { requestRegistration, verifyRegistration, login, logout, me, updateProfile, changePassword, requestPasswordReset, resetPasswordWithCode } = require("../controllers/authController");
const requireAuth = require("../middleware/auth");
router.post("/register/request", requestRegistration);
router.post("/register/verify", verifyRegistration);
router.post("/login", login);
router.post("/logout", requireAuth, logout);
router.get("/me", requireAuth, me);
router.put("/profile", requireAuth, updateProfile);
router.put("/password", requireAuth, changePassword);
router.post("/forgot-password", requestPasswordReset);
router.post("/reset-password", resetPasswordWithCode);
module.exports = router;
